name: CI/CD Flask Docker

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub using username + PAT
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cricsan_web:latest .

      # 4️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cricsan_web:latest

      # 5️⃣ Deploy to VPS using password
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cricsan_web:latest
            docker stop cricsan_web || true
            docker rm cricsan_web || true
            docker run -d -p 80:5000 --name cricsan_web ${{ secrets.DOCKER_USERNAME }}/cricsan_web:latest
